// <auto-generated />
namespace Data_Access_Layer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_user_info_updated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_user_info_updated));
        
        string IMigrationMetadata.Id
        {
            get { return "202508260719355_mig_user_info_updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
